services:
  # Definiamo il servizio come un "web service" generico...
  - type: web
    name: api-website
    env: static # ...ma specifichiamo che l'ambiente è statico.
    
    # Questo dice a Render di servire i file dalla cartella principale
    # senza eseguire un comando di avvio. È la chiave per un sito statico.
    staticPublishPath: ./
    
    # Aggiungiamo le istruzioni per la cache
    headers:
      - path: "/*"
        name: "Cache-Control"
        value: "no-cache, no-store, must-revalidate"
