services:
  # Definizione del servizio per il sito statico
  - type: static_site
    name: api-website
    env: static
    branch: main
    # Directory da pubblicare
    publishDir: ./
    # Istruzioni per la cache
    headers:
      - path: "/*"
        name: "Cache-Control"
        value: "no-cache, no-store, must-revalidate"
